volumes:
  postrges_data: {}

services:
  postgres:
    container_name: postgres-db
    image: postgres:16.0-alpine
    restart: always
    volumes:
      - postrges_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DB=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

  fastapi:
    container_name: fastapi
    build:
      context: ../../
      dockerfile: compose/dev/api/Dockerfile
    restart: on-failure
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DB=debug
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql+asyncpg://debug:debug@localhost:5432/debug
      - APP_NAME=FastAPI Microservice wich get information from tron
      - SECRET_KEY=my-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ADMIN_EMAIL=admin@admin.ru
      - ADMIN_PASSWORD=admin
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: /start
